### ISSUE TITLE
How to get Test Credit Cards

### ISSUE THREAD

**Issue by RajChanchal** [payfort/start-ios-sdk#2]
Hi,
I need to test payfort payment through credit cards how can I get test cards?

**Comment by vsiniak** [comment]
Hi @RajChanchal
You can find instructions for setting up test environment for testing payments here: http://www.payfort.com/get-started/
@alovak Do you have anything to add?

**Comment by alovak** [comment]
@RajChanchal do you have Start account or FORT? How did you know about this SDK?

At Payfort we have Start and FORT. This services are completely different (API, docs, etc.)

**Comment by RajChanchal** [comment]
@alovak I have FORT account associated with this email: mohamedmehadhamad@gmail.com
Unfortunately, I am unable to login through this email from: https://fort.payfort.com/account-login
Though, payfort is working fine in my iOS code, but I need some test cards to test it in sandbox mode. For your reference, my merchant identifier is: JUbYQVZn

**Comment by alovak** [comment]
@RajChanchal this SDK is not for FORT. It's for Start. It's mentioned in README.

Start has own docs here: https://docs.start.payfort.com/

If you are using FORT then here is the documentation for mobile integration with the FORT: https://docs.payfort.com/#fort-mobile-sdk

Please, check the platform you want to integrate with and use documentation for this platform.
